### ISSUE TITLE
Documentation for setting this up?

### ISSUE THREAD

**Issue by melodykramer** [ONA/ona-ethics#2]
Hello! I was wondering if you had any documentation for setting this up. I'm interested in playing around with your code. Thank you, Mel

**Comment by anekola** [comment]
Hi Melody! Just seeing this. I responded to Betsy a few days ago. I'm happy to chat with you in February about the project. For transparency's sake, no we don't have documentation. This theme was developed without open sourcing in mind a few years ago. I'm hoping to develop a better process for this on new projects in 2018.
